#!/bin/bash -eu
# Run continuous integration tests for jobserver.py
# Uses uv to run linting and formatting tools.
# Intended for use with CircleCI or Conda or VirtualEnv

# Informational and helpful when developing against multiple Python versions
echo "$(command -v python): $(python -V)"
set -x

# Unit testing runs the tests inside jobserver/test.py
python -m unittest -v jobserver.test

# PEP8 linting
uvx --from flake8 flake8 jobserver/

# Typehint linting requires a new-enough mypy
uvx --from "mypy>0.770" mypy jobserver/

# Finally, check for formatting issues
uvx --from "black<25" black --check --line-length 79 jobserver/
