#!/bin/bash -eu
# Run uv-based continuous integration tests for jobserver/

# Unit testing runs the tests inside jobserver/test.py
uv run -m unittest -v jobserver.test

# Run all examples to confirm they complete successfully
for ex in examples/ex[1-7]_*.py; do
    PYTHONPATH=. uv run "$ex"
done

# PEP8 linting
uvx --from flake8 flake8 jobserver/ examples/

# Typehint linting requires a new-enough mypy
uvx --from "mypy>0.770" mypy jobserver/

# Finally, check for formatting issues
uvx --from "black<25" black --check --line-length 79 jobserver/ examples/
