# Copyright (C) 2019-2026 Rhys Ulerich
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
"""Assemble a PyPI-flavored README from README.md and the examples."""

import os
import pathlib
import re
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
EXAMPLES = ROOT / "examples"
OUTPUT = ROOT / "README-PyPI.md"

# Inline markdown link [label](url); the lookbehind skips image links (![...]).
_LINK = re.compile(r"(?<!!)\[([^\]]+)\]\(([^)]+)\)")
_ABSOLUTE = re.compile(r"(https?://|mailto:|#)")


def main() -> None:
    """Write README-PyPI.md from README.md plus the inlined examples."""
    generator = pathlib.Path(__file__).resolve().relative_to(ROOT)
    banner = f"<!-- Generated by {generator} from README.md; do not edit. -->"
    flattened = flatten_relative_links(README.read_text()).rstrip("\n")
    content = f"{banner}\n\n{flattened}\n\n{inline_examples()}\n"
    # Stage to a sibling temp file, then atomically replace the target so a
    # mid-run failure can never truncate or clobber an existing README.
    fd, tmp = tempfile.mkstemp(dir=OUTPUT.parent, suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as handle:
            handle.write(content)
        os.chmod(tmp, 0o644)
        os.replace(tmp, OUTPUT)
    except BaseException:
        pathlib.Path(tmp).unlink(missing_ok=True)
        raise
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")


def flatten_relative_links(text: str) -> str:
    """Replace [label](relative) with label, keeping absolute links intact."""

    def replace(match: "re.Match[str]") -> str:
        label, url = match.group(1), match.group(2)
        return match.group(0) if _ABSOLUTE.match(url) else label

    lines = []
    for line in text.splitlines():
        if "![" in line:
            # Drop the CircleCI build-status badge; keep other image lines.
            if "Build Status" not in line:
                lines.append(line)
        else:
            lines.append(_LINK.sub(replace, line))
    return "\n".join(lines)


def inline_examples() -> str:
    """Return one '### name' code-block subsection per example, in order."""
    blocks = []
    for path in sorted(EXAMPLES.glob("ex*.py")):
        source = strip_license_header(path.read_text()).rstrip("\n")
        blocks.append(f"### Example {path.name}\n\n```python\n{source}\n```")
    return "\n\n".join(blocks)


def strip_license_header(source: str) -> str:
    """Drop the leading MPL comment header (and its trailing blank lines)."""
    lines = source.splitlines()
    index = 0
    while index < len(lines) and lines[index].startswith("#"):
        index += 1
    while index < len(lines) and not lines[index].strip():
        index += 1
    return "\n".join(lines[index:])


if __name__ == "__main__":
    main()
